# Generated by Django 5.2.13 on 2026-06-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Pin to a stable, long-standing pretixbase migration that already
        # creates the Organizer and Event tables (same approach as the
        # bundled stripe/paypal plugins). Avoids coupling to a specific
        # pretix release's latest migration.
        ('pretixbase', '0070_auto_20170719_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('order_code', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('list_uid', models.CharField(max_length=64)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('error_message', models.CharField(default='', max_length=255)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('subscriber_uid', models.CharField(default='', max_length=64)),
                ('consent_text', models.TextField(default='')),
                ('consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('locale', models.CharField(default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailwizz_sync_logs', to='pretixbase.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailwizz_sync_logs', to='pretixbase.organizer')),
            ],
            options={
                'ordering': ('-created',),
                'constraints': [models.UniqueConstraint(fields=('event', 'order_code', 'email', 'list_uid'), name='pretix_mailwizz_unique_sync')],
            },
        ),
    ]
